version: '3'

services:

  chitchat:
    container_name: chitchat
    image: rasa-faq:latest
    build: ./Dockerfiles
    ports:
      - "5005:5005"
    restart: always
    command: rasa run -m models/chitchat-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

  # hexaware:
  #   container_name: hexaware
  #   image: rasa-faq:latest
  #   ports:
  #     - "5006:5005"
  #   restart: always
  #   command: rasa run -m models/hexaware-model.tar.gz --enable-api  --log-file rasa.log --debug --cors "*"

# networks:
#   code-network:
#     driver: bridge

    # networks:
    #   - code-network