version: '3'

services:

  organization1:
    container_name: organization1
    image: rasa-faq:latest
    build: ./Dockerfiles
    ports:
      - "5005:5005"
    networks:
      - code-network
    restart: always
    command: rasa run -m models/chitchat-model.tar.gz -p 5005 --enable-api  --log-file rasa.log --debug --cors "*"

  hexaware:
    container_name: hexaware
    image: rasa-faq:latest
    ports:
      - "5006:5005"
    networks:
      - code-network
    restart: always
    command: rasa run -m models/hexaware-model.tar.gz -p 5006 --enable-api  --log-file rasa.log --debug --cors "*"

networks:
  code-network:
    driver: bridge
